### PR TITLE
Updated code to utilize NSNull's singleton

### PR DESCRIPTION
**Pull request by JamieREvans**

### CODE REVIEW

**Comment by jrturton** [comment]
the NSNull singleton stuff is fine, but I don't want to merge your other changes. I have my own preferences for formatting code. Do you want to amend the pull request?

**Comment by JamieREvans** [comment]
Oh no. Did I push some formatting changes as well? I only meant to push up
until the NSNull changes. I'll change that.

On Mar 15, 2014, at 7:07 AM, Richard Turton notifications@github.com
wrote:

the NSNull singleton stuff are fine, but I don't want to merge your other
changes. I have my own preferences for formatting code. Do you want to
amend the pull request?

## 

Reply to this email directly or view it on
GitHubhttps://github.com/jrturton/NSJSONSerialization-NSNullRemoval/pull/3#issuecomment-37723108
.

**Comment by jrturton** [comment]
I did it myself. Thanks for bringing it to my attention

**Comment by JamieREvans** [comment]
Thank you. I haven't been able to come back to this.

**Pull request closed without merging**
